// Copyright 2018 The PDFium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Original code copyright 2014 Foxit Software Inc. http://www.foxitsoftware.com

// NOTE: Ordered by hashcode for binary searching.
PCKT____(0x0811929du, "sourceSet", SourceSet, "http://www.xfa.org/schema/xfa-source-set/", kNoMatch, kSupportOne)
PCKT____(0x0b843dbau, "pdf", Pdf, "http://ns.adobe.com/xdp/pdf/", kCompleteMatch, kSupportOne)
PCKT____(0x0c56afbfu, "xdc", Xdc, "http://www.xfa.org/schema/xdc/", kNoMatch, kSupportOne)
PCKT____(0x0c56afccu, "xdp", Xdp, "http://ns.adobe.com/xdp/", kCompleteMatch, kSupportOne)
PCKT____(0x132a8fbcu, "xmpmeta", Xmpmeta, "http://ns.adobe.com/xmpmeta/", kNoMatch, kSupportMany)
PCKT____(0x48d004a8u, "xfdf", Xfdf, "http://ns.adobe.com/xfdf/", kNoMatch, kSupportOne)
PCKT____(0x4e1e39b6u, "config", Config, "http://www.xfa.org/schema/xci/", kNoMatch, kSupportOne)
PCKT____(0x5473b6dcu, "localeSet", LocaleSet, "http://www.xfa.org/schema/xfa-locale-set/", kNoMatch, kSupportOne)
PCKT____(0x6038580au, "stylesheet", Stylesheet, "http://www.w3.org/1999/XSL/Transform", kNoMatch, kSupportMany)
PCKT____(0x803550fcu, "template", Template,  "http://www.xfa.org/schema/xfa-template/", kNoMatch, kSupportOne)
PCKT____(0x8b036f32u, "signature", Signature, "http://www.w3.org/2000/09/xmldsig#", kNoMatch, kSupportOne)
PCKT____(0x99b95079u, "datasets", Datasets,  "http://www.xfa.org/schema/xfa-data/", kPrefixMatch, kSupportOne)
PCKT____(0xcd309ff4u, "form", Form, "http://www.xfa.org/schema/xfa-form/", kNoMatch, kSupportOne)
PCKT____(0xe14c801cu, "connectionSet", ConnectionSet, "http://www.xfa.org/schema/xfa-connection-set/", kNoMatch, kSupportOne)
PCKT____(0xffffffffu, "user", User, nullptr, kNoMatch, kSupportMany)
